on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates feeds and stats

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          feed_list: "https://avelino.run/index.xml"
      - name: dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: DEVTO
          feed_list: "https://dev.to/feed/avelino"

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update with recent activity'
          MAX_LINES: 8
